export function getCSSRules(state) {
  return {
    chartBackground : state['appearance.background'] ? `background-color: ${state['appearance.background']};` : 'background-color: inherit;',
    chartBorder : state['appearance.border'] ? `border-color: ${state['appearance.border']};` : 'border-color: inherit;',
    chartFont : state['appearance.font.family'] ? `font-family: "${state['appearance.font.family']}";` : 'font-family: inherit;',
    titleTextAlign : `text-align: ${state['title.textAlign']};`,
    titleColor : state['title.color'] ? `color: ${state['title.color']};` : 'color: inherit;',
    titleFontFamily : state['title.font.family'] ? `font-family: "${state['title.font.family']}";` : 'font-family: inherit;',
    titleFontSize : state['title.font.size'] !== 'auto' ? `font-size: ${state['title.font.size']}px;` : 'font-size: inherit;',
    titleFontBold : state['title.font.bold'] ? 'font-weight: bold;' : 'font-weight: inherit;',
    titleFontItalic : state['title.font.italic'] ? 'font-style: italic;' : 'font-style: inherit;',
    axisYLabelFont : state['axis.vertical.label.font.family'] ? `font-family: "${state['axis.vertical.label.font.family']}";` : 'font-family: inherit;',
    axisYLabelFontSize : state['axis.vertical.label.font.size'] !== 'auto' ? `font-size: ${state['axis.vertical.label.font.size']}px;` : 'font-size: inherit;',
    axisYLabelFontBold : state['axis.vertical.label.font.bold'] ? 'font-weight: bold;' : 'font-weight: inherit;',
    axisYLabelFontItalic : state['axis.vertical.label.font.italic'] ? 'font-style: italic;' : 'font-style: inherit;',
    axisYLabelColor : state['axis.vertical.label.color'] ? `fill: ${state['axis.vertical.label.color']};` : 'fill: inherit;',
    axisXLabelFont : state['axis.horizontal.label.font.family'] ? `font-family: "${state['axis.horizontal.label.font.family']}";` : 'font-family: inherit;',
    axisXLabelFontSize : state['axis.horizontal.label.font.size'] !== 'auto' ? `font-size: ${state['axis.horizontal.label.font.size']}px;` : 'font-size: inherit;',
    axisXLabelFontBold : state['axis.horizontal.label.font.bold'] ? 'font-weight: bold;' : 'font-weight: inherit;',
    axisXLabelFontItalic : state['axis.horizontal.label.font.italic'] ? 'font-style: italic;' : 'font-style: inherit;',
    axisXLabelColor : state['axis.horizontal.label.color'] ? `fill: ${state['axis.horizontal.label.color']};` : 'fill: inherit;',
    legendFont : state['legend.font.family'] ? `font-family: "${state['legend.font.family']}";` : 'font-family: inherit;',
    legendFontSize : state['legend.font.size'] !== 'auto' ? `font-size: ${state['legend.font.size']}px;` : 'font-size: inherit;',
    legendFontBold : state['legend.font.bold'] ? 'font-weight: bold;' : 'font-weight: inherit;',
    legendFontItalic : state['legend.font.italic'] ? 'font-style: italic;' : 'font-style: inherit;',
    legendColor : state['legend.color'] ? `color: ${state['legend.color']};` : 'color: inherit;',
    gridLineShow : state['grid.show'] ? 'stroke-opacity: 1;' : 'stroke-opacity: 0;',
    gridLineColor : state['grid.lines.color'] ? `stroke: ${state['grid.lines.color']}` : 'stroke: inherit;',
    subgridLineColor : state['subgrid.lines.color'] ? `stroke: ${state['subgrid.lines.count']}` : 'stroke: inherit;',
  }
}